// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type InputOrder struct {
	Item       string `json:"item"`
	User       string `json:"user"`
	Quantity   int    `json:"quantity"`
	City       string `json:"city"`
	Department string `json:"department"`
	Price      int    `json:"price"`
}

type Order struct {
	ID         string `json:"id"`
	Item       string `json:"item"`
	User       string `json:"user"`
	Quantity   int    `json:"quantity"`
	City       string `json:"city"`
	Department string `json:"department"`
	Price      int    `json:"price"`
}

type Report struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	OrderList []*Order  `json:"orderList"`
}
